osx_image: xcode6.4
language: objective-c
script: 
- CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO xcodebuild -workspace MoDevByProject.xcworkspace -scheme MoDevByProject clean build | xcpretty
- xcodebuild -workspace MoDevByProject.xcworkspace -scheme MoDevByProject -destination "name=iPad 2,OS=latest" clean test | xcpretty
